# Site settings
title: George Wolfstonecraft
email: gwolfstonecraft@domain.com
description: "Una obra de intriga literaria"
baseurl: ""
url: "https://wolfstonecraft.github.io"
#logo:
#cover:
author:
  name: George Wolfstonecraft
  image: //gravatar.com/userimage/117340007/051ec8d47b4370548966b39c5365b89b.jpg
  bio: false
  #location: Earth
  #website: https://wolfstonecraft.github.io
share: false

# Build settings
markdown: kramdown
permalink: /:title
paginate: 5
paginate_path: page/:num
