# Site settings
title: George Wolfstonecraft
email: gwolfstonecraft@domain.com
description: "Una obra de intriga literaria"
baseurl: ""
url: "https://wolfstonecraft.github.io"
logo: assets/images/ghost.png
cover: assets/images/cover.jpg
author:
  name: George Wolfstonecraft
  image: //gravatar.com/userimage/117340007/051ec8d47b4370548966b39c5365b89b.jpg
  bio: false
  #location: Earth
  #website: https://wolfstonecraft.github.io
subscribe: false  
share: false
timezone: Europe/Madrid

collections:
  my_categories:
    output: true
    permalink: /blog/category/:name/
  my_tags:
    output: true
    permalink: /blog/tag/:name/

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: my_categories
    values:
      layout: blog_by_category
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: blog_by_tag
  -
    scope:
      path: "project"
    values:
      layout: project

# Build settings
markdown: kramdown
permalink: /:title
paginate: 5
paginate_path: page/:num
